name: "Event Checker"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"    # every 15 minutes
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Get Latest Event
        id: get_latest_event
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: |
          node send_events.js
          git add .
      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update events.json"
          commit_options: "--signoff"
          commit_user_name: "GitHub Actions"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          file_pattern: "latest.id.json"
      - name: Push to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
